name: "Validate config"
on:
  push:
    branches:
      - master
      - beta-testing
jobs:
  validate:
    runs-on:
      - macos-latest
    steps:
      - name: "Download latest OpenCorePkg release"
        uses: robinraju/release-downloader@v1.4
        with:
          repository: "acidanthera/OpenCorePkg"
          latest: true
          filename: "*-RELEASE.zip"
          out-file-path: "oc"
      
      - name: "ls"
        run: "ls oc"
      
      - name: "Unzip OpenCorePkg"
        run: "unzip *.zip"
        working-directory: "./oc"

      - name: "pwd repo"
        run: "pwd"

      - name: "Run ocvalidate on EFI/OC/config.plist"
        run: "./oc/Utilities/ocvalidate/ocvalidate $GITHUB_WORKSPACE/EFI/OC/config.plist"
        




  
