name: "Update OpenCore binaries"
on:
  push:
    branches:
      - master
      - beta-testing
jobs:
  validate:
    name: "Update OpenCore binaries"
    runs-on:
      - macos-latest
    steps:
      - name: "Checkout to current repo"
        uses: actions/checkout@v3

      - name: "Download latest OpenCorePkg release"
        uses: robinraju/release-downloader@v1.4
        with:
          repository: "acidanthera/OpenCorePkg"
          latest: true
          filename: "*-RELEASE.zip"
          out-file-path: "oc"
      
      - name: "Unzip OpenCorePkg RELEASE version"
        run: "unzip *.zip"
        working-directory: "./oc"
      
      - name: "Update BOOT directory"
        run: "cp -r ./oc/X64/EFI/BOOT EFI/"

      - name: "Update OpenCore.efi binary"
        run: "cp -r ./oc/X64/EFI/OC/OpenCore.efi EFI/OC/OpenCore.efi"

      - name: "Update Drivers binaries"
        run: |
          for file in *; do
            echo $file
            cp $GITHUB_WORKSPACE/oc/X64/EFI/Drivers/$file $file
          done
        working-directory: "EFI/OC/Drivers"

      - name: "Remove oc directory"
        run: "rm -rf ./oc"
      
      - name: "Upload to artifacts"
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: "ocvalidate.txt"
          path: "./ocvalidate.txt"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ github.token }}
          commit-message: Updated OpenCore binaries
          body: |
            Updated OpenCore binaries
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          title: Update OpenCore binaries


  
