name: Workflow dispatch

on:
  push:
    branches: [ master ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  run-workflows:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Local Action Call
        id: ocvalidate
        uses: ./.github/workflows/ocvalidate.yml