name: Workflow dispatch

on:
  push:
    branches: [ master ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  call-ocvalidate:
    uses: ./.github/workflows/ocvalidate.yml
    secrets: inherit
  call-update-oc:
    uses: ./.github/workflows/update_oc.yml
    secrets: inherit
  call-release:
    uses: ./.github/workflows/release.yml
    secrets: inherit