name: Workflow dispatch

on:
  push:
    branches: [ master ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  run-workflows:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./actions/ocvalidate.yml
      - uses: ./actions/update_oc.yml
      - uses: ./actions/release.yml