name: Workflow dispatch

on:
  push:
    branches: [ master ]
  release:
    types: [published]
  workflow_dispatch:
  workflow_call:

jobs:
  ocvalidate:
    uses: ./.github/workflows/ocvalidate.yml
  update-oc-binaries:
    needs: ocvalidate
    uses: ./.github/workflows/update_oc.yml