name: Workflow dispatch

on:
  push:
    branches: [ master ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  run-workflows:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repo: ${{ github.repository }}
      - name: Local Action Call
        uses: ./.github/workflows/ocvalidate.yml