name: Workflow dispatch

on:
  push:
    branches: [ master ]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  run-workflows:
    uses: dreamwhite/ocvalidate-ci/.github/workflows/ocvalidate.yml@master